version: "3"
services:
  atcoder-pyenv:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORKDIR: /project/src
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    container_name: atcoder-pyenv
    tty: true
